// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function LearnReact(Props) {
  return React.createElement("a", {
              className: "App-link",
              href: "https://reactjs.org",
              rel: "noopener noreferrer",
              target: "_blank"
            }, "Learn React");
}

var make = LearnReact;

export {
  make ,
  
}
/* react Not a pure module */
